// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LayoutProvider from "./provider/LayoutProvider";
import ReactFormProvider from "./provider/ReactFormProvider";
import RecoilRootWrapper from "./provider/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootWrapper>
          <ReactFormProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </ReactFormProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
